image: python:3.9

stages:
  - format
  - test
  - security

before_script:
  - python3 setup.py install

flake8:
  stage: format
  script:
    - flake8 . --config .flake8

isort:
  stage: format
  script:
    - python3 -m isort --check --diff genbase

run_tests:
  stage: test
  script:
    - python3 -m pytest

  only:
    - master
    - branches
  artifacts:
    when: always

bandit:
  stage: security
  script:
    - bandit -r ./genbase -x /test
