[tool.poetry]
authors = ["Reik Stiebeling <reik.stiebeling@nwon.de>"]
description = "Some Django Wizardry"
homepage = "https://nwon.de"
include = ["README.md", "**/*.pyi"]
license = "MIT"
name = "nwon_django_toolbox"
readme = "README.md"
repository = "https://gitlab.com/nvon/pypi-packages/nwon-django-toolbox"
version = "0.1.5"

[tool.poetry.dependencies]
python = ">=3.7,<4.0"

django = ">=3.0" 
django-json-widget = "^1.1.1" 
django-polymorphic = "^3.1.0" 
django-rest-polymorphic = "^0.1.9" 
drf-yasg = "^1.20.0" 
nwon-baseline = "^0.1.19" 
pydantic = ">=1.8.2" 
pyhumps = "^3.0.2" # converting camelCase/PascalCase/snake_case
jsonref = "^0.2"
drf-spectacular = "^0.22.0"
jsonschema-to-openapi = "^0.2.1"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0" 
black = "^22.3.0" 
isort = "^5.9.3" # sort dependencies
mypy = "^0.910" # type checker
pylint = "^2.9.6" 
pytest = "^6.2.2" 

[tool.poetry.scripts]
prepare = "scripts.prepare:prepare"

# Code formatter black configuration
[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
include = '\.pyi?$'
line-length = 88

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.pyright]
