[project]
name = "ortools-puzzle-solvers"
version = "0.0.1a2"
description = "Constraint Solvers for common puzzles using OR-Tools."
authors = [
    { name = "Andrin Meier", email = "andrin@pricemeier.ch" },
]
license-expression = "MIT"
dependencies = [
    "ortools>=9.3.10497",
    "black>=22.3.0",
    "flake8>=4.0.1",
    "pytest>=7.1.1",
    "hypothesis>=6.40.0",
    "coverage>=6.3.2",
    "twine>=4.0.0",
]
requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/andrinmeier/solvers"

[tool.pdm.scripts]
lint = "flake8 ."
format = "black ."
test = "pdm run -v pytest tests"
testci = "coverage run -m pytest -v tests"
testreport = "coverage xml"

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
]
build-backend = "pdm.pep517.api"
