[tool.poetry]
name = "felucca-package-example"
version = "0.1.2"
description = ""
authors = ["franalgaba <f.algaba@outlook.es>"]
keywords = ["felucca"]
include = ["felucca_package_example/*.cairo", "felucca_package_example/*/*.cairo"]

[tool.poetry.dependencies]
python = ">=3.7.11,<3.9"
ecdsa = "^0.17.0"
fastecdsa = "^2.2.3"
sympy = "^1.10"
cairo-nile = "^0.4.0"
felucca = "^0.0.10"
"starknet.py" = "^0.2.0-alpha.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-asyncio = "^0.18.2"
black = {version = "^22.1.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"