[tool.poetry]
name = "dcevent"
version = "0.1.0"
description = "Placeholder package for internal development"
authors = ["Paul MÃ¼ller <dev@craban.de>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
