[tool.poetry]
name = "dimfred"
version = "0.5.0"
description = "Tools and abbrevations I use often."
authors = ["Dmitrij Vinokour <dimfred.1337@web.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">= 3.7"
tabulate = "^0.8.9"
easydict = "^1.9"
jsoncomment = "^0.4.2"
PyYAML = "^6.0"
pluck = "^0.2"
click = "^8.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
