[tool.poetry]
name = "sonusai"
version = "0.4.5"
description = "Framework for building deep neural network models for sound, speech, and voice AI"
authors = ["Chris Eddington <chris@aaware.com>", "Jason Calderwood <jason@aaware.com>"]
maintainers = ["Chris Eddington <chris@aaware.com>", "Jason Calderwood <jason@aaware.com>"]
homepage = "http://aaware.com"
license = "GPL-3.0-only"
readme = "README.rst"
include = ["sonusai/data/genmixdb.yml", "sonusai/data/whitenoise.wav"]

[tool.poetry.scripts]
sonusai = 'sonusai.main:main'
sonusai-evaluate = 'sonusai.evaluate:main'
sonusai-genft = 'sonusai.genft:main'
sonusai-genmix = 'sonusai.genmix:main'
sonusai-genmixdb = 'sonusai.genmixdb:main'
sonusai-gentcst = 'sonusai.gentcst:main'
sonusai-mkwav = 'sonusai.mkwav:main'
sonusai-predict = 'sonusai.predict:main'
sonusai-tplot = 'sonusai.tplot:main'
sonusai-version = 'sonusai.version:main'

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
sklearn = "^0.0"
h5py = ">=2.10.0,<2.11.0"
#h5py = "^3.6"
matplotlib = "^3.5"
docopt = "^0.6"
sox = "^1"
tensorflow = "==2.3.1"
#tensorflow = "^2.7"
keras2onnx = "^1"
#tf2onnx = "^1.9"
PyYAML = "^6.0"
tqdm = "^4.62"
pyaaware = "^1.3.15"
sh = "^1.14.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
