[tool.poetry]
name = "cmat2aset"
version = "0.1.0-alpha.6"
description = "correlation matrix to align set "
authors = ["ffreemt"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ffreemt/cmat2aset"
include = ["LICENSE", "cmat2aset/cmat2aset.pyc"]
exclude = ["cmat2aset/cmat2aset.py"]

[tool.poetry.dependencies]
python = ">=3.8.3,<4.0"
logzero = "^1.7.0"
icecream = "^2.1.1"
install = "^1.3.5"
numpy = "^1.22.3"
pandas = "^1.4.1"
sklearn = "^0.0"

[tool.poe.executor]
type = "poetry"

[tool.poe.tasks]
memo = "echo poe test"
test = "pytest tests"
build = "poetry build"
_publish = "poetry publish"
release = ["test", "build", "_publish"]
lint = { cmd = "pylint cmat2aset" }
format = "black tests cmat2aset"
docstyle = "pydocstyle --convention=google tests cmat2aset"
tunnel = {cmd = "ssh -CN ip_or_hostname_defined_in_hosts -L 9091:127.0.0.1:9091"}

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
flake8 = "^3.9.2"
pydocstyle = "^6.1.1"
# tbump = "^6.3.2"
poethepoet = "^0.10.0"
pyproject-flake8 = "^0.0.1-alpha.2"

# need to upgrade pytest
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --doctest-modules"
log_cli = true
testpaths = [
    "tests",
    # "integration",
]

[tool.black]
skip-string-normalization = 1

[tool.isort]
profile = "black"
multi_line_output = 3

# for project-flake8 (pflake8) E121 continuation line
[tool.flake8]
max-line-length = 88
ignore = "D203,E501"
extend-ignore = "E203,"
max-complexity = 25

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
